apiVersion: apps/v1
kind: Deployment
metadata:
  name: gocache-server
  labels:
    app: gocache-server
spec:
  selector:
    matchLabels:
      app: gocache-server
  replicas: 1
  template:
    metadata:
      labels:
        app: gocache-server
    spec:
      containers:
        - name: master
          image: gocache-server
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080