apiVersion: v1
kind: Service
metadata:
  name: gocache-server
  labels:
    app: gocache-server
spec:
  type: NodePort
  ports:
    - port: 10001
      targetPort: 10001
      name: server
  selector:
    app: gocache-server